server:
  port: 8765
  servlet:
    context-path: /service-feign
spring:
  application:
    name: service-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
feign:
  hystrix:
    enabled: true
