spring:
  application:
    name: config-client
  cloud:
    config:
#      uri: http://localhost:8887/
      profile: dev
      label: chapter8
      discovery:
        service-id: config-server
        enabled: true
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8881
  servlet:
    context-path: /config-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
