spring:
  cloud:
    config:
      profile: dev
      label: master
      uri: http://localhost:8888
    discovery:
      serviceId: config-server
      enabled: true
  application:
    name: config-client
server:
  port: 8881
  servlet:
    context-path: /config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka