server:
  port: 8084
  servlet:
    context-path: /breed-pig-service
spring:
  application: breed-pig-service
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true
      label: master #分支
      profile: dev #环境