server:
  port: 8084
  servlet:
    context-path: /breed-pig
spring:
  application: breed-pig
  cloud:
    config:
      uri: http://localhost:8888 #配置服务器
      label: master #分支
      profile: dev #环境