server:
  port: 8084
  servlet:
    context-path: /breed-pig-service
spring:
  application: breed-pig-service
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true
      label: master #分支
      profile: dev #环境
#    bus:
#      enabled: true
#      trace:
#        enabled: true
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#management:
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh