spring:
  cloud:
    config:
      server:
        git:
          searchPaths: respo
          uri: https://github.com/vanniuner/springcloud/
          username:
          password:
      label: chapter8
  application:
    name: config-server
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/