spring:
  cloud:
    config:
      server:
        git:
          searchPaths: cloud-config
          uri: https://github.com/vanniuner/springcloud/
      label: master
  application:
    name: config-server
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/