spring:
  cloud:
    config:
      server:
        git:
          password:
          searchPaths: respo
          uri: https://github.com/forezp/SpringcloudConfig/
          username:
      label: master
  application:
    name: config-server
server:
  port: 8878
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka